import type { NodeConfig } from "@cairn/shared";

export const NODES: Record<string, NodeConfig> = {
  gatekeeper: {
    name: "gatekeeper",
    allowed_callers: ["system"],
    allowed_tools: [],
    memory_access: ["hot"],
    memory_write: ["hot"],
    max_runtime_seconds: 10,
    max_tokens_per_call: 1000,
    assigned_model: "gpt-4o-mini",
    local_model: "phi3.5:latest",
  },
  planner: {
    name: "planner",
    allowed_callers: ["orchestrator"],
    allowed_tools: ["memory_read"],
    memory_access: ["hot", "warm"],
    memory_write: ["hot", "warm"],
    max_runtime_seconds: 120,
    max_tokens_per_call: 10000,
    assigned_model: "gpt-4o",
    local_model: "qwen2.5-coder:7b",
  },
  executor: {
    name: "executor",
    allowed_callers: ["planner", "orchestrator"],
    allowed_tools: ["memory_read", "memory_write", "ledger_write", "web_search", "fetch_url", "vector_search", "calendar_read", "gmail_read", "goals_read", "goals_update", "tasks_read", "tasks_create", "tasks_complete", "note_create", "research_ingest", "browser_navigate", "browser_click", "browser_screenshot", "model_pull"],
    memory_access: ["hot", "warm"],
    memory_write: ["hot", "warm"],
    max_runtime_seconds: 300,
    max_tokens_per_call: 5000,
    assigned_model: "gpt-4o-mini",
    local_model: "phi3:mini",
  },
  critic: {
    name: "critic",
    allowed_callers: ["executor", "orchestrator"],
    allowed_tools: ["memory_read", "goals_read"],
    memory_access: ["hot", "warm"],
    memory_write: [],
    max_runtime_seconds: 60,
    max_tokens_per_call: 4000,
    assigned_model: "gpt-4o-mini",
    local_model: "qwen2.5-coder:7b",
  },
  web_locked: {
    name: "web_locked",
    allowed_callers: ["planner", "executor", "orchestrator"],
    allowed_tools: [],
    memory_access: [],
    memory_write: [],
    max_runtime_seconds: 60,
    max_tokens_per_call: 4000,
    assigned_model: "gpt-4o-mini",
    local_model: "phi3.5:latest",
  },
  logger: {
    name: "logger",
    allowed_callers: ["all"],
    allowed_tools: ["ledger_write"],
    memory_access: [],
    memory_write: [],
    max_runtime_seconds: 5,
    max_tokens_per_call: 0,
    assigned_model: "none",
    local_model: "none",
  },
  vision_worker: {
    name: "vision_worker",
    allowed_callers: ["planner", "executor", "orchestrator"],
    allowed_tools: [],       // No tools — image in, text out
    memory_access: ["hot"],  // Hot only — no goals, no warm/cold memory
    memory_write: [],        // Cannot write memory (containment)
    max_runtime_seconds: 60,
    max_tokens_per_call: 4000,
    assigned_model: "gpt-4o",
    local_model: "llava-llama3:8b",
  },
  web_agent: {
    name: "web_agent",
    allowed_callers: ["orchestrator"],
    allowed_tools: ["browser_navigate", "browser_click", "browser_type", "browser_press", "browser_screenshot", "browser_close", "browser_observe"],
    memory_access: ["hot", "warm"],
    memory_write: ["hot", "warm"],
    max_runtime_seconds: 300,
    max_tokens_per_call: 5000,
    assigned_model: "gpt-4o-mini",
    local_model: "phi3.5:latest",
  },

  // ---- V2 Pipeline Nodes ----

  classifier: {
    name: "classifier",
    allowed_callers: ["system", "orchestrator"],
    allowed_tools: [],
    memory_access: [],
    memory_write: [],
    max_runtime_seconds: 10,
    max_tokens_per_call: 500,
    assigned_model: "gpt-4o-mini",
    local_model: "phi3.5:latest",
  },
  builder: {
    name: "builder",
    allowed_callers: ["system", "scheduler"],
    allowed_tools: ["memory_read"],
    memory_access: ["hot", "warm"],
    memory_write: ["hot", "warm"],
    max_runtime_seconds: 7200, // 2 hours
    max_tokens_per_call: 4096,
    assigned_model: "gpt-4o",
    local_model: "qwen2.5-coder:7b",
  },
  responder: {
    name: "responder",
    allowed_callers: ["system", "orchestrator"],
    allowed_tools: [],
    memory_access: ["hot", "warm"],
    memory_write: [],
    max_runtime_seconds: 15,
    max_tokens_per_call: 1000,
    assigned_model: "gpt-4o-mini",
    local_model: "phi3.5:latest",
  },
  skill_executor: {
    name: "skill_executor",
    allowed_callers: ["system", "orchestrator"],
    allowed_tools: ["memory_read", "memory_write", "ledger_write", "web_search", "fetch_url", "vector_search", "calendar_read", "gmail_read", "goals_read", "goals_update", "tasks_read", "tasks_create", "tasks_complete", "note_create", "research_ingest", "browser_navigate", "browser_click", "browser_screenshot", "model_pull"],
    memory_access: ["hot", "warm"],
    memory_write: ["hot", "warm"],
    max_runtime_seconds: 300,
    max_tokens_per_call: 0,
    assigned_model: "none",
    local_model: "none",
  },
  specialist: {
    name: "specialist",
    allowed_callers: ["orchestrator"],
    allowed_tools: [],
    memory_access: [],
    memory_write: [],
    max_runtime_seconds: 10,
    max_tokens_per_call: 500,
    assigned_model: "gpt-4o-mini",
    local_model: "phi3.5:latest",
  },
};

/** Allowed transitions: from -> to[] */
export const GRAPH_EDGES: Record<string, string[]> = {
  // V1 legacy (kept for backward compatibility)
  system: ["gatekeeper", "classifier"],
  gatekeeper: ["planner", "logger", "web_agent", "vision_worker"],
  planner: ["executor", "web_locked", "vision_worker", "logger", "skill_executor"],
  executor: ["critic", "web_locked", "vision_worker", "logger"],
  critic: ["executor", "logger"],
  vision_worker: ["logger"],
  web_locked: ["logger"],
  web_agent: ["logger"],
  logger: [],

  // V2 pipeline
  classifier: ["responder", "skill_executor", "planner", "logger", "specialist"],
  responder: ["logger"],
  skill_executor: ["logger"],
  specialist: ["skill_executor", "logger"],
};
