
import { SkillManifest } from "@cairn/shared";

export const DEFAULT_SKILLS_MANIFEST: SkillManifest[] = [
    {
        id: "task.create",
        version: "1.0.0",
        description: "Create a new task for the user.",
        inputSchema: {
            type: "object",
            properties: {
                title: { type: "string", description: "Task title" },
                type: { type: "string", enum: ["one-off", "recurring"], description: "Task type" },
                due_date: { type: "string", description: "Due date (ISO format)" },
                scheduled_date: { type: "string", description: "Scheduled date (YYYY-MM-DD)" },
            },
            required: ["title"],
        },
        outputSchema: { type: "object", properties: { success: { type: "boolean" }, output: { type: "string" } } },
        riskLevel: "low",
        enabled: true,
        tags: ["productivity", "core"],
        requiresPlanner: false,
        costEstimate: "trivial",
    },
    {
        id: "task.read",
        version: "1.0.0",
        description: "Read current tasks, optionally filtered by status.",
        inputSchema: {
            type: "object",
            properties: {
                status: { type: "string", enum: ["todo", "done", "archived"], description: "Filter by status" },
            },
            required: [],
        },
        outputSchema: { type: "object", properties: { success: { type: "boolean" }, output: { type: "string" } } },
        riskLevel: "low",
        enabled: true,
        tags: ["productivity", "core"],
        requiresPlanner: false,
        costEstimate: "trivial",
    },
    {
        id: "task.complete",
        version: "1.0.0",
        description: "Mark a task as completed.",
        inputSchema: {
            type: "object",
            properties: {
                task_id: { type: "string", description: "ID of the task to complete" },
            },
            required: ["task_id"],
        },
        outputSchema: { type: "object", properties: { success: { type: "boolean" }, output: { type: "string" } } },
        riskLevel: "low",
        enabled: true,
        tags: ["productivity", "core"],
        requiresPlanner: false,
        costEstimate: "trivial",
    },
    {
        id: "calendar.read",
        version: "1.0.0",
        description: "Read calendar events for the next N days.",
        inputSchema: {
            type: "object",
            properties: {
                days: { type: "number", description: "Number of days to look ahead (default 1)" },
            },
            required: [],
        },
        outputSchema: { type: "object", properties: { success: { type: "boolean" }, output: { type: "string" } } },
        riskLevel: "low",
        enabled: true,
        tags: ["productivity", "external"],
        requiresPlanner: false,
        costEstimate: "cheap",
    },
    {
        id: "web.search",
        version: "1.0.0",
        description: "Search the web using DuckDuckGo.",
        inputSchema: {
            type: "object",
            properties: {
                query: { type: "string", description: "Search query" },
            },
            required: ["query"],
        },
        outputSchema: { type: "object", properties: { success: { type: "boolean" }, output: { type: "string" } } },
        riskLevel: "medium", // Web access implies some risk/cost
        enabled: true,
        tags: ["research", "external"],
        requiresPlanner: false,
        costEstimate: "cheap",
    },
    {
        id: "web.fetch",
        version: "1.0.0",
        description: "Fetch content from a URL (first 2000 chars).",
        inputSchema: {
            type: "object",
            properties: {
                url: { type: "string", description: "URL to fetch" },
            },
            required: ["url"],
        },
        outputSchema: { type: "object", properties: { success: { type: "boolean" }, output: { type: "string" } } },
        riskLevel: "medium",
        enabled: true,
        tags: ["research", "external"],
        requiresPlanner: false,
        costEstimate: "cheap",
    },
    {
        id: "memory.read",
        version: "1.0.0",
        description: "Read a value from memory (hot, warm, or cold tier).",
        inputSchema: {
            type: "object",
            properties: {
                tier: { type: "string", enum: ["hot", "warm", "cold"], description: "Memory tier" },
                key: { type: "string", description: "Memory key" },
            },
            required: ["tier", "key"],
        },
        outputSchema: { type: "object", properties: { success: { type: "boolean" }, output: { type: "string" } } },
        riskLevel: "low",
        enabled: true,
        tags: ["core", "memory"],
        requiresPlanner: false,
        costEstimate: "trivial",
    },
    {
        id: "memory.write",
        version: "1.0.0",
        description: "Write a value to memory (hot or warm tier).",
        inputSchema: {
            type: "object",
            properties: {
                tier: { type: "string", enum: ["hot", "warm"], description: "Memory tier" },
                key: { type: "string", description: "Memory key" },
                value: { description: "Value to store" },
            },
            required: ["tier", "key", "value"],
        },
        outputSchema: { type: "object", properties: { success: { type: "boolean" }, output: { type: "string" } } },
        riskLevel: "low",
        enabled: true,
        tags: ["core", "memory"],
        requiresPlanner: false,
        costEstimate: "trivial",
    },
    {
        id: "note.create",
        version: "1.0.0",
        description: "Create a persistent note in the dashboard.",
        inputSchema: {
            type: "object",
            properties: {
                content: { type: "string", description: "Note content" },
            },
            required: ["content"],
        },
        outputSchema: { type: "object", properties: { success: { type: "boolean" }, output: { type: "string" } } },
        riskLevel: "low",
        enabled: true,
        tags: ["productivity", "core"],
        requiresPlanner: false,
        costEstimate: "trivial",
    },
    {
        id: "goal.read",
        version: "1.0.0",
        description: "Read active goals the user is working toward.",
        inputSchema: {
            type: "object",
            properties: {},
            required: [],
        },
        outputSchema: { type: "object", properties: { success: { type: "boolean" }, output: { type: "string" } } },
        riskLevel: "low",
        enabled: true,
        tags: ["productivity", "core"],
        requiresPlanner: false,
        costEstimate: "trivial",
    },
    {
        id: "goal.update",
        version: "1.0.0",
        description: "Update a goal (status, timeline, confidence).",
        inputSchema: {
            type: "object",
            properties: {
                goal_id: { type: "string", description: "Goal ID to update" },
                status: { type: "string", description: "New status" },
                confidence: { type: "number", description: "New confidence (0-1)" },
                timeline_message: { type: "string", description: "Timeline event message" },
                timeline_type: { type: "string", description: "Timeline event type" },
            },
            required: ["goal_id"],
        },
        outputSchema: { type: "object", properties: { success: { type: "boolean" }, output: { type: "string" } } },
        riskLevel: "low",
        enabled: true,
        tags: ["productivity", "core"],
        requiresPlanner: false,
        costEstimate: "trivial",
    },
    {
        id: "vector.search",
        version: "1.0.0",
        description: "Semantic search over long-term memory documents.",
        inputSchema: {
            type: "object",
            properties: {
                query: { type: "string", description: "Search query" },
            },
            required: ["query"],
        },
        outputSchema: { type: "object", properties: { success: { type: "boolean" }, output: { type: "string" } } },
        riskLevel: "low",
        enabled: true,
        tags: ["memory", "core"],
        requiresPlanner: false,
        costEstimate: "medium",
    },
    {
        id: "email.read",
        version: "1.0.0",
        description: "Read recent emails from Gmail.",
        inputSchema: {
            type: "object",
            properties: {
                max_results: { type: "number", description: "Max emails to return (default 5)" },
            },
            required: [],
        },
        outputSchema: { type: "object", properties: { success: { type: "boolean" }, output: { type: "string" } } },
        riskLevel: "medium", // PII access
        enabled: true,
        tags: ["productivity", "external"],
        requiresPlanner: false,
        costEstimate: "cheap",
    },
    {
        id: "research.ingest",
        version: "1.0.0",
        description: "Ingest web content or PDF into long-term memory.",
        inputSchema: {
            type: "object",
            properties: {
                url: { type: "string", description: "URL to ingest" },
            },
            required: ["url"],
        },
        outputSchema: { type: "object", properties: { success: { type: "boolean" }, output: { type: "string" } } },
        riskLevel: "medium",
        enabled: true,
        tags: ["research", "memory"],
        requiresPlanner: false,
        costEstimate: "expensive",
    },
    {
        id: "weather.get",
        version: "1.0.0",
        description: "Get current weather and forecast.",
        inputSchema: {
            type: "object",
            properties: {
                location: { type: "string", description: "City or location name" },
            },
            required: ["location"],
        },
        outputSchema: { type: "object", properties: { success: { type: "boolean" }, output: { type: "string" } } },
        riskLevel: "low",
        enabled: true,
        tags: ["external"],
        requiresPlanner: false,
        costEstimate: "trivial",
    },
    {
        id: "system.model_pull",
        version: "1.0.0",
        description: "Download a logical model (Ollama) to the local system.",
        inputSchema: {
            type: "object",
            properties: {
                model: { type: "string", description: "Model name (e.g. qwen2.5-coder:7b)" },
            },
            required: ["model"],
        },
        outputSchema: { type: "object", properties: { success: { type: "boolean" }, output: { type: "string" } } },
        riskLevel: "high", // High bandwidth/disk usage
        enabled: true,
        tags: ["system"],
        requiresPlanner: false,
        costEstimate: "expensive",
    },
];
