/**
 * Planner V2 — Cairn V2
 * 
 * Receives an ActionContract and produces a Plan with PlanStep[].
 * Constrained to registered skills only. Cannot invent tools.
 * Respects maxToolCalls. Defines termination.
 */

import { z } from "zod";
import type { ActionContract, Plan, PlanStep } from "@cairn/shared";
import { newId, now, bus } from "@cairn/shared";
import { callLLM } from "../llm.js";
import { listSkills, getSkillDefinition } from "../skill-registry.js";

// ---- Zod Schema ----

const PlanStepSchema = z.object({
    skillId: z.string(),
    arguments: z.record(z.string(), z.any()),
    workerClass: z.enum(["default", "light"]).optional(),
    parallelGroup: z.string().min(1).max(40).optional(),
    maxRetries: z.number().int().min(0).max(3).optional(),
    escalationSkillId: z.string().optional(),
    confidenceHint: z.number().min(0).max(1).optional(),
});

const PlanOutputSchema = z.object({
    steps: z.array(PlanStepSchema).min(1).max(10),
    maxToolCalls: z.number().int().min(1).max(20),
    riskLevel: z.enum(["low", "medium", "high"]),
    governance: z.object({
        maxParallelLightWorkers: z.number().int().min(1).max(10).optional(),
        maxRetriesPerStep: z.number().int().min(0).max(3).optional(),
        escalationMode: z.enum(["none", "final-step"]).optional(),
    }).optional(),
});

// ---- System Prompt ----

function buildPlannerPrompt(skills: { id: string; description: string; inputSchema: object }[]): string {
    const skillList = skills.map((s) => `  - ${s.id}: ${s.description}\n    Schema: ${JSON.stringify(s.inputSchema)}`).join("\n");
    const maxParallelLightWorkers = Number.parseInt(process.env.CAIRN_MAX_LIGHT_WORKERS || "4", 10);

    return `You are a planner for Cairn, a personal AI assistant.
You receive a task description and must produce a step-by-step plan using ONLY the available skills listed below.

## Available Skills
${skillList}

## Output Format (STRICT JSON)
{
  "steps": [
    {
      "skillId": "skill.id",
      "arguments": { ... },
      "workerClass": "default" | "light",
      "parallelGroup": "optional-group-id",
      "maxRetries": 0-3,
      "escalationSkillId": "optional.skill.id",
      "confidenceHint": 0.0-1.0
    },
    ...
  ],
  "maxToolCalls": number,
  "riskLevel": "low" | "medium" | "high",
  "governance": {
    "maxParallelLightWorkers": 1-10,
    "maxRetriesPerStep": 0-3,
    "escalationMode": "none" | "final-step"
  }
}


## Rules
- ONLY use skillIds from the Available Skills list. Never invent new skills.
- Each step must have valid arguments matching the skill's requirements.
- Order steps logically — if step 2 depends on step 1's output, say so.
- Keep plans minimal. Don't add unnecessary steps.
- maxToolCalls should be the total number of skill invocations.
- Use \`workerClass: "light"\` for independent, low-risk reads that can run in parallel.
- Any shared \`parallelGroup\` can run concurrently; keep groups small and safe.
- max parallel light workers cap is ${maxParallelLightWorkers}. Never exceed it.
- Use \`maxRetries\` only where transient failures are likely.
- Set \`confidenceHint\` per step (higher when input certainty is high).
- riskLevel: "low" for read-only, "medium" for writes, "high" for external-facing actions.
- Respond with ONLY valid JSON. No markdown, no explanation.

## Variable Substitution
If a step depends on the output of a previous step (like an ID generated by a create/read tool), use the syntax \`{{stepN.output.jsonPath}}\`, where N is the simple step index (1-based).
Example:
- Step 1: \`goal.read\` (returns \`{"active": [{"id": "g-123"}]}\`)
- Step 2: \`goal.update\` with \`goal_id\`: \`{{step1.output.active.0.id}}\`

## BE CREATIVE WITH COMPOSITION
Think creatively about how to combine available skills to achieve the goal:
- Research tasks: web.search → memory.write (to save findings) → note.create (to summarize)
- Organizing: task.read + goal.read → note.create (to compile a status update)
- Remembering: memory.write (store info) + task.create (set a follow-up reminder)
- Checking in: calendar.read + goal.read + task.read → compose a briefing

## CRITICAL INSTRUCTIONS
- Do NOT assume you have information. If the user asks for research, you MUST use 'web.search' or 'research.ingest'.
- Do NOT just create a note saying you did research if you haven't done it yet.
- If the Primary Skill Hint is 'goal.read' but the user wants research, you must ALSO add 'web.search'.
- Build a complete plan. Don't be lazy.

Even if there's no single perfect skill, a combination of available skills can often accomplish what the user needs. ALWAYS produce at least one step — never return an empty plan.`;

}

// ---- Planner ----

const MAX_PLAN_STEPS = 10;
const MAX_TOOL_CALLS = 20;

export async function createPlan(
    contract: ActionContract,
    userText: string,
): Promise<{ plan: Plan | null; cost_usd: number; error?: string }> {
    const skills = listSkills();
    const systemPrompt = buildPlannerPrompt(skills);

    const userMessage = `Task: ${contract.justification}
User said: "${userText}"
${contract.skillId ? `Primary skill hint: ${contract.skillId}` : ""}
${contract.arguments ? `Known arguments: ${JSON.stringify(contract.arguments)}` : ""}

Create a plan to accomplish this.`;

    try {
        const response = await callLLM(
            {
                model: "gpt-4o-mini",
                systemPrompt,
                userMessage,
                maxTokens: 600,
                responseFormat: "json_object",
                temperature: 0,
            },
            "planner",
            "plan-" + newId().slice(0, 8),
        );

        const parsed = tryParsePlan(response.content);
        if (!parsed) {
            bus.emit("log:entry", {
                id: newId(),
                timestamp: now(),
                type: "error",
                content: `Planner parse failed. Raw: ${response.content.substring(0, 200)}`,
            });

            return {
                plan: null,
                cost_usd: response.cost.cost_usd,
                error: "Failed to parse planner output",
            };
        }

        // Validate all skillIds exist
        const invalidSteps = parsed.steps.filter(
            (step) => !getSkillDefinition(step.skillId),
        );

        if (invalidSteps.length > 0) {
            const invalidIds = invalidSteps.map((s) => s.skillId).join(", ");
            bus.emit("log:entry", {
                id: newId(),
                timestamp: now(),
                type: "error",
                content: `Planner referenced unknown skills: ${invalidIds}. Filtering them out.`,
            });

            // Filter out invalid steps rather than failing entirely
            parsed.steps = parsed.steps.filter(
                (step) => getSkillDefinition(step.skillId) !== undefined,
            );

            if (parsed.steps.length === 0) {
                return {
                    plan: null,
                    cost_usd: response.cost.cost_usd,
                    error: `All planned skills were invalid: ${invalidIds}`,
                };
            }
        }

        // Enforce limits
        parsed.steps = parsed.steps.slice(0, MAX_PLAN_STEPS).map((step) => ({
            ...step,
            workerClass: step.workerClass ?? "default",
            maxRetries: Math.min(Math.max(step.maxRetries ?? 0, 0), 3),
            confidenceHint: step.confidenceHint === undefined ? 0.7 : Math.min(Math.max(step.confidenceHint, 0), 1),
        }));
        parsed.maxToolCalls = Math.min(parsed.maxToolCalls, MAX_TOOL_CALLS);
        parsed.governance = {
            maxParallelLightWorkers: Math.min(Math.max(parsed.governance?.maxParallelLightWorkers ?? 4, 1), 10),
            maxRetriesPerStep: Math.min(Math.max(parsed.governance?.maxRetriesPerStep ?? 1, 0), 3),
            escalationMode: parsed.governance?.escalationMode ?? "final-step",
        };

        return { plan: parsed, cost_usd: response.cost.cost_usd };
    } catch (err) {
        const errorMsg = err instanceof Error ? err.message : String(err);
        return { plan: null, cost_usd: 0, error: errorMsg };
    }
}

// ---- Parse Helper ----

function tryParsePlan(content: string): Plan | null {
    try {
        const raw = JSON.parse(content.trim());
        const result = PlanOutputSchema.safeParse(raw);
        if (result.success) {
            return result.data;
        }
        console.warn("[planner-v2] Schema validation failed:", result.error.issues);
        return null;
    } catch {
        return null;
    }
}
